#!/bin/bash

echo 'NORMAL20'
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "NORMAL.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'NORMAL40'
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "NORMAL.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'NORMAL60'
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "NORMAL.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'NORMAL80'
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "NORMAL.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'NORMAL100'
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "NORMAL.*turnaround" | awk '{printf "%s,",$10}'

echo ' '
echo 'FIFO20'
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "FIFO.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'FIFO40'
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "FIFO.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'FIFO60'
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "FIFO.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'FIFO80'
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "FIFO.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'FIFO100'
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "FIFO.*turnaround" | awk '{printf "%s,",$10}'

echo ' '
echo 'RR20'
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "RR.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RR40'
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "RR.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RR60'
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "RR.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RR80'
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "RR.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RR100'
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "RR.*turnaround" | awk '{printf "%s,",$10}'

echo ' '
echo 'RAS20'
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "RAS.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RAS40'
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "RAS.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RAS60'
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "RAS.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RAS80'
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "RAS.*turnaround" | awk '{printf "%s,",$10}'
echo ' '
echo 'RAS100'
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "RAS.*turnaround" | awk '{printf "%s,",$10}'