#!/bin/bash

echo 'normal_20 = ['
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "NORMAL.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'normal_40 = ['
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "NORMAL.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'normal_60 = ['
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "NORMAL.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'normal_80 = ['
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "NORMAL.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'normal_100 = ['
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "NORMAL.*latency" | awk '{printf "%s,",$6}'
echo ']'

echo 'fifo_20 = ['
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "FIFO.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'fifo_40 = ['
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "FIFO.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'fifo_60 = ['
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "FIFO.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'fifo_80 = ['
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "FIFO.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'fifo_100 = ['
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "FIFO.*latency" | awk '{printf "%s,",$6}'
echo ']'

echo 'rr_20 = ['
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "RR.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'rr_40 = ['
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "RR.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'rr_60 = ['
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "RR.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'rr_80 = ['
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "RR.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'rr_100 = ['
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "RR.*latency" | awk '{printf "%s,",$6}'
echo ']'

echo 'ras_20 = ['
cat ../src/project2/problem2/test_res/benchmark_20_task_res.txt | grep "RAS.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'ras_40 = ['
cat ../src/project2/problem2/test_res/benchmark_40_task_res.txt | grep "RAS.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'ras_60 = ['
cat ../src/project2/problem2/test_res/benchmark_60_task_res.txt | grep "RAS.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'ras_80 = ['
cat ../src/project2/problem2/test_res/benchmark_80_task_res.txt | grep "RAS.*latency" | awk '{printf "%s,",$6}'
echo ']'
echo 'ras_100 = ['
cat ../src/project2/problem2/test_res/benchmark_100_task_res.txt | grep "RAS.*latency" | awk '{printf "%s,",$6}'
echo ']'